-- MySQL Script generated by MySQL Workbench
-- Wed Sep 10 21:37:37 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd2` ;

-- -----------------------------------------------------
-- Schema bd2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd2` DEFAULT CHARACTER SET utf8 ;
USE `bd2` ;

-- -----------------------------------------------------
-- Table `bd2`.`datas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd2`.`datas` ;

CREATE TABLE IF NOT EXISTS `bd2`.`datas` (
  `id` INT NOT NULL,
  `dia_de_criacao` DATE NOT NULL,
  `dia_de_concluido` DATE NULL,
  `dia_de_fazendo` DATE NULL,
  `dia_de_pausado` DATE NULL,
  `data_limite` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd2`.`projetos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd2`.`projetos` ;

CREATE TABLE IF NOT EXISTS `bd2`.`projetos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(50) NULL,
  `datas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_projetos_datas1_idx` (`datas_id` ASC) VISIBLE,
  CONSTRAINT `fk_projetos_datas1`
    FOREIGN KEY (`datas_id`)
    REFERENCES `bd2`.`datas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd2`.`pessoas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd2`.`pessoas` ;

CREATE TABLE IF NOT EXISTS `bd2`.`pessoas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd2`.`tarefas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd2`.`tarefas` ;

CREATE TABLE IF NOT EXISTS `bd2`.`tarefas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` ENUM('a-fazer', 'em-andamento', 'concluido') NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `projetos_id` INT NOT NULL,
  `criador_id` INT NOT NULL COMMENT 'criador da tarefa',
  `datas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tarefas_projetos1_idx` (`projetos_id` ASC) VISIBLE,
  INDEX `fk_tarefas_pessoas1_idx` (`criador_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_tarefas_datas1_idx` (`datas_id` ASC) VISIBLE,
  CONSTRAINT `fk_tarefas_projetos1`
    FOREIGN KEY (`projetos_id`)
    REFERENCES `bd2`.`projetos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tarefas_pessoas1`
    FOREIGN KEY (`criador_id`)
    REFERENCES `bd2`.`pessoas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tarefas_datas1`
    FOREIGN KEY (`datas_id`)
    REFERENCES `bd2`.`datas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd2`.`equipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd2`.`equipe` ;

CREATE TABLE IF NOT EXISTS `bd2`.`equipe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd2`.`equipe_has_pessoas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd2`.`equipe_has_pessoas` ;

CREATE TABLE IF NOT EXISTS `bd2`.`equipe_has_pessoas` (
  `equipe_id` INT NOT NULL,
  `pessoas_id` INT NOT NULL,
  `tag` VARCHAR(50) NULL COMMENT 'exemplo: lider, desenvolvedor, dba, da, estagiario',
  INDEX `fk_equipe_has_pessoas_pessoas1_idx` (`pessoas_id` ASC) VISIBLE,
  INDEX `fk_equipe_has_pessoas_equipe1_idx` (`equipe_id` ASC) VISIBLE,
  CONSTRAINT `fk_equipe_has_pessoas_equipe1`
    FOREIGN KEY (`equipe_id`)
    REFERENCES `bd2`.`equipe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipe_has_pessoas_pessoas1`
    FOREIGN KEY (`pessoas_id`)
    REFERENCES `bd2`.`pessoas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd2`.`tarefas_has_pessoas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd2`.`tarefas_has_pessoas` ;

CREATE TABLE IF NOT EXISTS `bd2`.`tarefas_has_pessoas` (
  `tarefas_id` INT NOT NULL,
  `pessoas_id` INT NOT NULL,
  INDEX `fk_tarefas_has_pessoas_pessoas1_idx` (`pessoas_id` ASC) VISIBLE,
  INDEX `fk_tarefas_has_pessoas_tarefas1_idx` (`tarefas_id` ASC) VISIBLE,
  CONSTRAINT `fk_tarefas_has_pessoas_tarefas1`
    FOREIGN KEY (`tarefas_id`)
    REFERENCES `bd2`.`tarefas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tarefas_has_pessoas_pessoas1`
    FOREIGN KEY (`pessoas_id`)
    REFERENCES `bd2`.`pessoas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd2`.`projetos_has_pessoas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd2`.`projetos_has_pessoas` ;

CREATE TABLE IF NOT EXISTS `bd2`.`projetos_has_pessoas` (
  `projetos_id` INT NOT NULL,
  `pessoas_id` INT NOT NULL,
  `tag` VARCHAR(50) NULL COMMENT 'exemplo: criador, cliente',
  INDEX `fk_projetos_has_pessoas_pessoas1_idx` (`pessoas_id` ASC) VISIBLE,
  INDEX `fk_projetos_has_pessoas_projetos1_idx` (`projetos_id` ASC) VISIBLE,
  CONSTRAINT `fk_projetos_has_pessoas_projetos1`
    FOREIGN KEY (`projetos_id`)
    REFERENCES `bd2`.`projetos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projetos_has_pessoas_pessoas1`
    FOREIGN KEY (`pessoas_id`)
    REFERENCES `bd2`.`pessoas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd2`.`projetos_has_equipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd2`.`projetos_has_equipe` ;

CREATE TABLE IF NOT EXISTS `bd2`.`projetos_has_equipe` (
  `projetos_id` INT NOT NULL,
  `equipe_id` INT NOT NULL,
  `tag` VARCHAR(50) NULL COMMENT 'exemplo: desenvolvedores, designers',
  INDEX `fk_projetos_has_equipe_equipe1_idx` (`equipe_id` ASC) VISIBLE,
  INDEX `fk_projetos_has_equipe_projetos1_idx` (`projetos_id` ASC) VISIBLE,
  CONSTRAINT `fk_projetos_has_equipe_projetos1`
    FOREIGN KEY (`projetos_id`)
    REFERENCES `bd2`.`projetos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projetos_has_equipe_equipe1`
    FOREIGN KEY (`equipe_id`)
    REFERENCES `bd2`.`equipe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
