-- MySQL Script generated by MySQL Workbench
-- Wed Sep 10 21:37:37 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd2` ;

-- -----------------------------------------------------
-- Schema bd2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd2` DEFAULT CHARACTER SET utf8 ;
USE `bd2` ;

-- -----------------------------------------------------
-- Table `bd2`.`datas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd2`.`datas` ;

CREATE TABLE IF NOT EXISTS `bd2`.`datas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `criacao` DATE NOT NULL,
  `fazendo` DATE NULL,
  `conclusao` DATE NULL,
  `limite` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd2`.`projetos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd2`.`projetos` ;

CREATE TABLE IF NOT EXISTS `bd2`.`projetos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(50) NULL,
  `data_id` INT NOT NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd2`.`pessoas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd2`.`pessoas` ;

CREATE TABLE IF NOT EXISTS `bd2`.`pessoas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd2`.`tarefas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd2`.`tarefas` ;

CREATE TABLE IF NOT EXISTS `bd2`.`tarefas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` ENUM('a-fazer', 'em-andamento', 'concluido') NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `projeto_id` INT NOT NULL,
  `criador_id` INT NOT NULL COMMENT 'criador da tarefa',
  `data_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd2`.`equipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd2`.`equipes` ;

CREATE TABLE IF NOT EXISTS `bd2`.`equipes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd2`.`equipe_has_pessoas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd2`.`equipes_has_pessoas` ;

CREATE TABLE IF NOT EXISTS `bd2`.`equipes_has_pessoas` (
  `equipe_id` INT NOT NULL,
  `pessoa_id` INT NOT NULL,
  `tag` VARCHAR(24) NULL COMMENT 'mongodb Objectid')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd2`.`tarefas_has_pessoas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd2`.`tarefas_has_pessoas` ;

CREATE TABLE IF NOT EXISTS `bd2`.`tarefas_has_pessoas` (
  `tarefa_id` INT NOT NULL,
  `pessoa_id` INT NOT NULL,
  `tag` VARCHAR(24) NULL COMMENT 'mongodb Objectid')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd2`.`projetos_has_pessoas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd2`.`projetos_has_pessoas` ;

CREATE TABLE IF NOT EXISTS `bd2`.`projetos_has_pessoas` (
  `projeto_id` INT NOT NULL,
  `pessoa_id` INT NOT NULL,
  `tag` VARCHAR(24) NULL COMMENT 'mongodb Objectid')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd2`.`projetos_has_equipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd2`.`projetos_has_equipes` ;

CREATE TABLE IF NOT EXISTS `bd2`.`projetos_has_equipes` (
  `projeto_id` INT NOT NULL,
  `equipe_id` INT NOT NULL,
  `tag` VARCHAR(24) NULL COMMENT 'mongodb Objectid')
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
